//! Validate the APT->SWF bytecode bridge against the real corpus: every action
//! stream in every APT file is lowered to SWF AVM1 and then re-parsed by the
//! `swf` crate's own AVM1 reader. If Ruffle's parser accepts all of them, the
//! generated bytecode is well-formed.

use std::path::{Path, PathBuf};

use apt::actions::{ActionStream, Instruction};
use apt::{AptFile, Character, CharacterSlot, Control};
use apt_convert::bytecode::apt_to_swf_actions;

fn corpus_root() -> Option<PathBuf> {
    let p = PathBuf::from("/home/stephan/Devel/APT");
    p.is_dir().then_some(p)
}

fn find_apt(root: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(root) else {
        return;
    };
    for e in entries.flatten() {
        let p = e.path();
        if p.is_dir() {
            find_apt(&p, out);
        } else if p.extension().and_then(|e| e.to_str()) == Some("apt")
            && p.with_extension("const").is_file()
        {
            out.push(p);
        }
    }
}

fn collect_streams<'a>(file: &'a AptFile, out: &mut Vec<&'a ActionStream>) {
    fn frames<'a>(fs: &'a [apt::Frame], out: &mut Vec<&'a ActionStream>) {
        for f in fs {
            for c in &f.controls {
                match c {
                    Control::Action(s) | Control::InitAction { actions: s, .. } => out.push(s),
                    Control::PlaceObject(p) => {
                        if let Some(blocks) = &p.clip_actions {
                            for b in blocks {
                                out.push(&b.actions);
                            }
                        }
                    }
                    _ => {}
                }
            }
        }
    }
    frames(&file.movie.frames, out);
    for slot in &file.movie.characters {
        if let CharacterSlot::Character(c) = slot {
            match c {
                Character::Sprite(s) => frames(&s.frames, out),
                Character::Button(b) => {
                    for a in &b.actions {
                        out.push(&a.actions);
                    }
                }
                _ => {}
            }
        }
    }
}

/// Recursively check that no `Try` instruction is present (we don't translate
/// those to SWF yet); such streams are skipped rather than failing.
fn has_try(s: &ActionStream) -> bool {
    s.instructions.iter().any(|i| match i {
        Instruction::Try { .. } => true,
        Instruction::DefineFunction { body, .. } | Instruction::DefineFunction2 { body, .. } => {
            has_try(body)
        }
        _ => false,
    })
}

#[test]
fn corpus_bytecode_is_valid_swf() {
    let Some(root) = corpus_root() else {
        eprintln!("corpus not present; skipping");
        return;
    };
    let mut files = Vec::new();
    find_apt(&root, &mut files);

    let mut streams = 0usize;
    let mut lowered_ok = 0usize;
    let mut reparse_ok = 0usize;
    let mut skipped_try = 0usize;
    let mut failures = Vec::new();

    for path in &files {
        let apt_data = std::fs::read(path).unwrap();
        let const_data = std::fs::read(path.with_extension("const")).unwrap();
        let Ok(file) = AptFile::read(&apt_data, &const_data) else {
            continue;
        };

        let mut ss = Vec::new();
        collect_streams(&file, &mut ss);
        for s in ss {
            if has_try(s) {
                skipped_try += 1;
                continue;
            }
            streams += 1;
            let bytes = match apt_to_swf_actions(s) {
                Ok(b) => b,
                Err(e) => {
                    failures.push(format!("{}: lower: {e}", path.display()));
                    continue;
                }
            };
            lowered_ok += 1;
            // Re-parse with the swf crate's AVM1 reader.
            match parse_all_actions(&bytes) {
                Ok(()) => reparse_ok += 1,
                Err(e) => failures.push(format!("{}: reparse: {e}", path.display())),
            }
        }
    }

    eprintln!(
        "bytecode: {streams} streams, {lowered_ok} lowered, {reparse_ok} re-parsed by swf crate, {skipped_try} skipped (Try)"
    );
    for f in failures.iter().take(20) {
        eprintln!("  FAIL {f}");
    }
    assert!(failures.is_empty(), "{} bytecode failures", failures.len());
}

/// Drive the swf crate's AVM1 reader across a whole action buffer.
fn parse_all_actions(data: &[u8]) -> Result<(), String> {
    use swf::avm1::read::Reader;
    use swf::avm1::types::Action;
    let mut reader = Reader::new(data, 6);
    let mut remaining = data.len();
    loop {
        if reader.get_ref().is_empty() {
            return Ok(());
        }
        match reader.read_action() {
            Ok(Action::End) => return Ok(()),
            Ok(_) => {
                // Guard against a stuck reader.
                let now = reader.get_ref().len();
                if now >= remaining {
                    return Ok(());
                }
                remaining = now;
            }
            Err(e) => return Err(e.to_string()),
        }
    }
}
